// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxYZ44QZLebZSIeu4ZG5l_4eOFdfI0g8I',
    appId: '1:727246633037:web:c40c8325223d9e44c5c404',
    messagingSenderId: '727246633037',
    projectId: 'quotidien-c04f5',
    authDomain: 'quotidien-c04f5.firebaseapp.com',
    storageBucket: 'quotidien-c04f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4KezCwyZMbCkvKyTeD4fL_g1n0uImDhY',
    appId: '1:727246633037:android:8de6dc2de8119887c5c404',
    messagingSenderId: '727246633037',
    projectId: 'quotidien-c04f5',
    storageBucket: 'quotidien-c04f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeFPCCHE0UleDkuBT9CkWLebRdHB8cuBU',
    appId: '1:727246633037:ios:b7a99330949b1e18c5c404',
    messagingSenderId: '727246633037',
    projectId: 'quotidien-c04f5',
    storageBucket: 'quotidien-c04f5.firebasestorage.app',
    iosBundleId: 'com.example.quotidien',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeFPCCHE0UleDkuBT9CkWLebRdHB8cuBU',
    appId: '1:727246633037:ios:b7a99330949b1e18c5c404',
    messagingSenderId: '727246633037',
    projectId: 'quotidien-c04f5',
    storageBucket: 'quotidien-c04f5.firebasestorage.app',
    iosBundleId: 'com.example.quotidien',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxYZ44QZLebZSIeu4ZG5l_4eOFdfI0g8I',
    appId: '1:727246633037:web:6acaef28e4fc705dc5c404',
    messagingSenderId: '727246633037',
    projectId: 'quotidien-c04f5',
    authDomain: 'quotidien-c04f5.firebaseapp.com',
    storageBucket: 'quotidien-c04f5.firebasestorage.app',
  );

}